# -*- coding: utf-8 -*-
"""61.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HC6z3k2SwGvwLt9R4ZTSqbtxwgDWL8Qr
"""

import numpy as np
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt

x = [2, 3, 4, 5, 6, 7]
y = [12, 12, 32, 16, 22, 25]

linear_interp = interp1d(x, y, kind='linear')

quadratic_interp = interp1d(x, y, kind='quadratic')

x_interp = np.linspace(2, 7, 100)

y_linear_interp = linear_interp(x_interp)
y_quadratic_interp = quadratic_interp(x_interp)

plt.scatter(x, y, label='Data Points', color='red')
plt.plot(x_interp, y_linear_interp, label='Linear Spline', linestyle='--')
plt.plot(x_interp, y_quadratic_interp, label='Quadratic Spline', linestyle='--')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()
plt.grid()
plt.show()